use windows-latest runner

diff --git a/.github/workflows/Build-Experimental.yml b/.github/workflows/Build-Experimental.yml
--- a/.github/workflows/Build-Experimental.yml
+++ b/.github/workflows/Build-Experimental.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     strategy:
       fail-fast:  true
 
@@ -16,17 +16,21 @@ jobs:
           ref: ${{github.event.inputs.tag}}
       
       - name: 'Setup Pre-Requisites & Prepare Staging Area'
+        shell:  |
+                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
         run:  |
               apt-get update && apt-get install wget unzip
               cd '${{github.workspace}}'
-              wget 'https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.ConsoleLinux-1.6.5.zip' && unzip './*.zip'
-              mv WolvenKit\ CLI\ Linux/ WolvenKit
-              chmod -R 0770 ./WolvenKit
-              mkdir -p '${{github.workspace}}/STAGING/archive/pc/mod' && mkdir -p '${{github.workspace}}/STAGING/r6/scripts'
+              wget -O WolvenKit.zip 'https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.Console-1.6.5.zip'
+              Expand-Archive -Path WolvenKit.zip -DestinationPath .
+              mv "WolvenKit CLI" WolvenKit
+              mkdir '${{github.workspace}}/STAGING/archive/pc/mod'
+              mkdir '${{github.workspace}}/STAGING/r6/scripts'
               cp '${{github.workspace}}/redscript/REALISTICCOMBATOVERHAUL.reds' '${{github.workspace}}/STAGING/r6/scripts'
-              ls -lAgh
-                  
+
       - name: 'Pack .archive'
+        shell:  |
+                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
         run:  |
               cd '${{github.workspace}}/basegame_REALISM'
               ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
diff --git a/.github/workflows/Generate-Release.yml b/.github/workflows/Generate-Release.yml
--- a/.github/workflows/Generate-Release.yml
+++ b/.github/workflows/Generate-Release.yml
@@ -12,7 +12,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     strategy:
       fail-fast:  true
 
@@ -20,22 +20,26 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{github.event.inputs.tag}}
+          fetch-depth: 0
       
-      - name: 'Setup Pre-Requisites & Prepare Staging Area'
-        run:  |
-              apt-get update && apt-get install wget unzip
-              cd '${{github.workspace}}'
-              wget 'https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.ConsoleLinux-1.6.5.zip' && unzip './*.zip'
-              mv WolvenKit\ CLI\ Linux/ WolvenKit
-              chmod -R 0770 ./WolvenKit
-              mkdir -p '${{github.workspace}}/STAGING/archive/pc/mod' && mkdir -p '${{github.workspace}}/STAGING/r6/scripts'
-              cp '${{github.workspace}}/redscript/REALISTICCOMBATOVERHAUL.reds' '${{github.workspace}}/STAGING/r6/scripts'
-              ls -lAgh
+      - name:  'Setup Pre-Requisites & Prepare Staging Area'
+        shell: |
+               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
+        run:   |
+               cd '${{github.workspace}}'
+               wget -O WolvenKit.zip 'https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.Console-1.6.5.zip'
+               Expand-Archive -Path WolvenKit.zip -DestinationPath .
+               mv "WolvenKit CLI" WolvenKit
+               mkdir '${{github.workspace}}/STAGING/archive/pc/mod'
+               mkdir '${{github.workspace}}/STAGING/r6/scripts'
+               cp '${{github.workspace}}/redscript/REALISTICCOMBATOVERHAUL.reds' '${{github.workspace}}/STAGING/r6/scripts'
                   
-      - name: 'Pack .archive'
-        run:  |
-              cd '${{github.workspace}}/basegame_REALISM'
-              ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
+      - name:  'Pack .archive'
+        shell: |
+               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
+        run:   |
+               cd '${{github.workspace}}/basegame_REALISM'
+               ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
         
       - name:   'Upload Artifact'
         uses:   actions/upload-artifact@v2
@@ -43,19 +47,22 @@ jobs:
           name: 'HARDCORE44-ARCO'
           path: '${{github.workspace}}/STAGING/*'
           
-      - name:   'Create Release Archive'
-        run:    |
-                cd '${{github.workspace}}/STAGING'
-                zip -T9r HARDCORE44-ARCO.zip .
-            
       - name:   'Get Release Information'
         id:     get_version
+        shell:  bash
         run:    |
                 if [ "${{github.event.inputs.tag}}" == "" ];  then TAG="${GITHUB_REF/refs\/tags\//}"; else TAG="${{github.event.inputs.tag}}" ; fi
                 if [ "$TAG" == "refs/heads/main" ]; then TAG=""; fi
                 echo ::set-output name=VERSION::$TAG
                 echo ::set-output name=NAME::"Release $TAG"
                 
+      - name:   'Create Release Archive'
+        shell:  |
+                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
+        run:    |
+                cd '${{github.workspace}}/STAGING'
+                Compress-Archive -Path ./* -DestinationPath "./HARDCORE44-ARCO-$TAG.zip"
+            
       - name:   'Create Github Release'
         uses:   softprops/action-gh-release@v1
         with:
@@ -65,4 +72,4 @@ jobs:
           name:                     ${{ steps.get_version.outputs.NAME }}
           generate_release_notes:   true
           fail_on_unmatched_files:  true
-          files:                    '${{ github.workspace }}/STAGING/HARDCORE44-ARCO.zip'
+          files:                    './*.zip'
