remove tag information from the release to fix broke-ass workflow runs

diff --git a/.github/workflows/Generate-Release.yml b/.github/workflows/Generate-Release.yml
--- a/.github/workflows/Generate-Release.yml
+++ b/.github/workflows/Generate-Release.yml
@@ -11,7 +11,7 @@ on:
         required: false
 
 jobs:
-  pack-archive:
+  build:
     runs-on: windows-latest
     strategy:
       fail-fast:  true
@@ -20,6 +20,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{github.event.inputs.tag}}
+          fetch-depth: 0
       
       - name:  'Setup Pre-Requisites & Prepare Staging Area'
         shell: |
@@ -46,41 +47,18 @@ jobs:
           name: 'HARDCORE44-ARCO'
           path: '${{github.workspace}}/STAGING/*'
 
-  create-release:
-    runs-on:  ubuntu-latest
-    needs:    pack-archive
-    strategy:
-      fail-fast: true
-
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: '${{github.event.inputs.tag}}'
-          fetch-depth: 0
-
-      - uses:   actions/download-artifact@v2
-        with:
-          name: 'HARDCORE44-ARCO'
-          path: '${{github.workspace}}'
-
-      - id:     get_version
-        shell:  bash
-        run:    |
-                if [ "${{github.event.inputs.tag}}" == "" ];  then TAG="${GITHUB_REF/refs\/tags\//}"; else TAG="${{github.event.inputs.tag}}" ; fi
-                if [ "$TAG" == "refs/heads/main" ]; then TAG=""; fi
-                echo ::set-output name=VERSION::$TAG
-                echo ::set-output name=NAME::"Release $TAG"
-                
       - name:   'Create Release Archive'
-        run:    zip -T9r HARDCORE44-ARCO.zip ./*
+        shell:  |
+                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
+        run:    |
+                cd '${{github.workspace}}/STAGING'
+                Compress-Archive -Path ./* -DestinationPath "../HARDCORE44-ARCO-$TAG.zip"
             
       - name:   'Create Github Release'
         uses:   softprops/action-gh-release@v1
         with:
           draft:                    true
           prerelease:               false
-          tag_name:                 ${{ steps.get_version.outputs.VERSION }}
-          name:                     ${{ steps.get_version.outputs.NAME }}
           generate_release_notes:   true
           fail_on_unmatched_files:  true
           files:                    './*.zip'
